default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: hubbado-upsert_version_development

test:
  <<: *default
  url: <%= ENV["DATABASE_URL"] || "postgres://localhost:5432" %>
  database: hubbado-upsert_version_test
